name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Smoke check
        run: |
          python -V
          echo "CI OK"
